### ISSUE TITLE
[LG] Switch template not matching cases

### ISSUE THREAD

**Issue by sschutten** [microsoft/botbuilder-dotnet#5508]
## Version
4.12.2

## Describe the bug
The language generation [Switch template](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0#switch-template) doesn't match a case, even though the values match and are both of type integer. When both the switch and the case are explicitly converted to an integer, the Switch template matches the case correctly.

Given `score` has a value of `1`...

... this doesn't work. The output is `Unknown (1 == 1 ? True)`
```
- SWITCH: ${score}
    - CASE: ${1}
        - Low
    - CASE: ${5}
        - High
    - DEFAULT:
        - Unknown (${score} == 1 ? ${score == 1})
```

... however, this works. The output is `Low`
```
- SWITCH: ${int(score)}
    - CASE: ${int(1)}
        - Low
    - CASE: ${int(5)}
        - High
    - DEFAULT:
        - Unknown
```

## To Reproduce
I've created a bot using the Bot Framework Composer to demonstrate the unexpected behavior.
1. Clone the following repository: [lg-switch-issue](https://github.com/sschutten/lg-switch-issue)
2. Run the bot from the Bot Framework Composer
3. Open the bot with the Bot Framework Emulator.

## Expected behavior
The expected behavior is that the cases match if <variable> == <value> is true.

## Screenshots
![image](https://user-images.githubusercontent.com/10097564/115565898-14b5af00-a2ba-11eb-8d68-8d64533b79f2.png)
